apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: hadoop
spec:
  nodeSelector:
    topology.kubernetes.io/region: us-west
    topology.kubernetes.io/zone: fullerton
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: shared-pvc
  initContainers:
  - name: init-dns
    image: busybox
    command: ["sh", "-c"]
    args:
      - "echo $(hostname -i) > /config/master_ip"
    volumeMounts:
    - name: config-volume
      mountPath: /config
  containers:
  - name: master
    image: "gitlab-registry.nrp-nautilus.io/focegueda/hadoop-test/hadoop:latest"
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 2Gi
        cpu: 1000m
    ports:
    - containerPort: 8088
    - containerPort: 9864
    - containerPort: 9870
    - containerPort: 8042
    volumeMounts:
    - name: config-volume
      mountPath: /config
    command: ["bash", "-c"]
    args: [
      "echo 'Reloading bashrc'; \
       source ~/.bashrc; \
       sleep 30; \
       echo 'Fetching node IPs and updating /etc/hosts'; \
       export SLAVE01_IP=$(cat /config/slave01_ip); \
       export SLAVE02_IP=$(cat /config/slave02_ip); \
       echo $SLAVE01_IP slave01 >> /etc/hosts; \
       echo $SLAVE02_IP slave02 >> /etc/hosts; \
       echo 'Updated /etc/hosts'; \
       echo 'master\nslave01\nslave02' > $HADOOP_HOME/etc/hadoop/workers; \
       echo 'Starting HDFS and YARN'; \
       sleep 30; \
       hdfs namenode -format -force -nonInteractive; \
       start-dfs.sh; \
       start-yarn.sh; \
       hdfs --daemon start namenode; \
       tail -f /dev/null; "
    ]