apiVersion: v1
kind: Pod
metadata:
  name: slave01
  labels:
    app: hadoop
spec:
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: shared-pvc
  initContainers:
  - name: init-dns
    image: busybox
    command: ["sh", "-c"]
    args:
      - "echo $(hostname -i) > /config/slave01_ip"
    volumeMounts:
    - name: config-volume
      mountPath: /config
  containers:
  - name: slave01
    image: "gitlab-registry.nrp-nautilus.io/focegueda/hadoop-test/hadoop:latest"
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 2Gi
        cpu: 1000m
    ports:
    - containerPort: 9864
    - containerPort: 8042
    volumeMounts:
    - name: config-volume
      mountPath: /config
    command: ["bash", "-c"]
    args: [
      "source ~/.bashrc; \
       sleep 30; \
       echo 'Fetching node IPs and updating /etc/hosts'; \
       export MASTER_IP=$(cat /config/master_ip); \
       export SLAVE02_IP=$(cat /config/slave02_ip); \
       echo $MASTER_IP master >> /etc/hosts; \
       echo $SLAVE02_IP slave02 >> /etc/hosts; \
       echo 'Updated /etc/hosts'; \
       echo 'awaiting for master to start'; \
       while ! nc -z master 9870; do sleep 3; done; \
       tail -f /dev/null; "
    ]