apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  storageClassName: rook-cephfs-fullerton
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi