apiVersion: v1
kind: Pod
metadata:
  name: solo
  labels:
    k8s-app: pytorch
spec:
  nodeSelector:
    topology.kubernetes.io/region: us-west
    topology.kubernetes.io/zone: fullerton
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: datasets-pvc
  containers:
  - name: solo
    image: "gitlab-registry.nrp-nautilus.io/focegueda/data-curator-and-model-dispatcher/sparktorchkafka:latest"
    resources:
      limits:
        memory: 16Gi
        cpu: 10000m
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        cpu: 10000m
        nvidia.com/gpu: 1
    volumeMounts:
    - name: config-volume
      mountPath: /config
    command: ["bash", "-c"]
    args: [
      "apt-get install unzip -y; \
       apt-get install zip -y; \
       apt-get install libxcb-xinerama0 -y; \
       apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 -y; \
       echo \"export QT_DEBUG_PLUGINS=1\" >> /root/.bashrc; \
       echo \"export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/miniconda3/lib/python3.12/site-packages/PyQt5/Qt5/plugins/platforms\" >> /root/.bashrc; \
       echo \"export KAGGLE_USERNAME=\" >> /root/.bashrc; \
       echo \"export KAGGLE_KEY=\" >> /root/.bashrc; \
       echo \"SPARK_CLASSPATH=$(find /usr/local/spark/jars -name '*.jar' | tr '\n' ':')\" >> /root/.bashrc; \
       echo 'SPARK_WORKER_PORT=7078' >> /root/.bashrc; \
       echo 'SPARK_WORKER_OPTS=\"-Dspark.worker.resource.gpu.amount=1 -Dspark.worker.resource.gpu.discoveryScript=/opt/sparkRapidsPlugin/getGpusResources.sh\"' >> /usr/local/spark/conf/spark-env.sh; \
       echo 'SPARK_WORKER_OPTS=\"-Dspark.worker.resource.gpu.amount=1 -Dspark.worker.resource.gpu.discoveryScript=/opt/sparkRapidsPlugin/getGpusResources.sh\"' >> /root/.bashrc; \
       echo \"SPARK_CLASSPATH=$(find /usr/local/spark/jars -name '*.jar' | tr '\n' ':')\" >> /root/.bashrc; \
       echo \"\" >> /root/.bashrc; \
       source /usr/local/miniconda3/bin/activate; \
       conda install -c conda-forge transformers -y; \
       conda install -c conda-forge diffusers -y; \
       conda install seaborn -y; \
       conda install matplotlib -y; \
       conda install scikit-learn -y; \
       conda install pyqt -y; \
       echo \"y\"| pip install pyqt5; \
       conda install -c conda-forge kaggle -y; \
       conda install -c conda-forge pillow -y; \
       conda install -c conda-forge libxcb -y; \
       echo \"y\" | pip install torchsummary ; \
       mkdir -p /config/Codebase; \
       echo 'Reloading bashrc'; \
       . /root/.bashrc; \
       . /etc/profile; \
       /usr/sbin/sshd; \
       echo 'Downloading Kaggle Dataset, Please Wait For This To Complete'; \
       mkdir -p /config/AI_Human_Generated_Images; \
       kaggle datasets download alessandrasala79/ai-vs-human-generated-dataset -p /config; \
       unzip /config/ai-vs-human-generated-dataset.zip -d /config/AI_Human_Generated_Images; \
       rm -rf /config/ai-vs-human-generated-dataset.zip; \
       echo 'Directories Set Up'; \
       chmod +x /opt/sparkRapidsPlugin/getGpusResources.sh; \
       echo 'solo' > /usr/local/spark/conf/workers; \
       ./usr/local/spark/sbin/start-all.sh --host solo --port 7077; \
       tail -f /dev/null;
       "
    ]